### ISSUE TITLE
Create an app to allow realtime adjustment of the blur

### ISSUE THREAD

**Issue by slavingia** [slavingia/metazoom#1]
Instead of a fixed number in the source code, allow a UI to update it, accessible from the menubar.

This requires two big things: turning the plugin into an app (that autoloads the plugin), and a menubar item to allow modification of this variable.

### Todos

- [ ] Design
- [ ] New app within repo
- [ ] Update instructions to install plugin/app
- [ ] Real-time preview of screen when sliding range input
